apiVersion: v1
kind: ReplicationController
metadata:
  name: cfssl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cfssl
    spec:
      containers:
        - name: cfssl
          image: pmdcosta/cfssl:latest
          command:
          - "sleep"
          - "3600"
          volumeMounts:
            - mountPath: /ssl/data/production/ca
              name: ca
      volumes:
        - name: ca
          secret:
            secretName: qold-ssl-ca-key
