apiVersion: v1
kind: ReplicationController
metadata:
  name: cfssl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cfssl
    spec:
      containers:
      - name: cfssl
        image: pmdcosta/cfssl:latest
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
            - mountPath: /ssl/ca
              name: qold-ca-key
      volumes:
        - name: qold-ca-key
          secret:
            secretName: qold-ca-key
